name: Docker Security CI/CD

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  secure-docker-pipeline:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build and push Docker image
      run: |
        IMAGE= ${{ secrets.DOCKER_USERNAME }}/insecure-image:ci-latest
        docker build -t $IMAGE 03-image-security
        docker push $IMAGE

    - name: Install Cosign
      run: |
        curl -Lo cosign https://github.com/sigstore/cosign/releases/latest/download/cosign-linux-amd64
        chmod +x cosign
        sudo mv cosign /usr/local/bin/cosign

    - name: Decode and save Cosign key
      run: |
        echo "${{ secrets.COSIGN_KEY }}" | base64 -d > cosign.key

    - name: Sign Docker image with Cosign
      env:
        COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}
      run: |
        IMAGE=${{ secrets.DOCKER_USERNAME }}/insecure-image:ci-latest
        cosign sign --key cosign.key $IMAGE
